FROM caddy:builder AS builder

RUN caddy-builder github.com/caddyserver/nginx-adapter 

FROM caddy:alpine

ENV XDG_DATA_HOME /var/data
COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]
